### PR TITLE
Add extra_args

### PR DESCRIPTION
**Pull request by xeroc**
Allow to provide custom arguments, such as `--begin` or `--end` or any other.

### CODE REVIEW

**Comment by adept** [comment]
Thanks! Do you see any reason not to use "$@" instead? I am going to change HLEDGER_ARGS to $@ - it would be easier to the end user

**Comment by xeroc** [comment]
> Thanks! Do you see any reason not to use "$@" instead? I am going to change HLEDGER_ARGS to $@ - it would be easier to the end user

Works too :D
Thanks

**Comment by xeroc** [comment]
Thinking about it, the difference is that you cannot define `$@` via environmental variables in docker-compose, but have to change the entrypoint to append extra args.

Decision is of course yours, but IMHO docker-compose files would look more consistent if people weren't forced to update the entrypoint command.

**Comment by adept** [comment]
Actually, we can do both things! Pushed the change just now.

**Pull request merged**
